---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
    when: ansible_distribution == "Ubuntu"

  - name: install php for apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install httpd package
    dnf:
      name: httpd
    when: ansible_distribution == "Fedora"

  - name: install php for apache2
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Fedora"
